### ISSUE TITLE
Configuration File Not Loaded Successfully When Path is Specified

### ISSUE THREAD

**Issue by SubutaDan** [manusant/spark-swagger#30]
Here are source code for and output from a simple program that seem to show that the config file is in the specified location and can be read, but that spark-swagger can't find it or perhaps can't parse it.

```
/*******************************************************************************
 * Copyright (c) 2017, 2018, 2019, 2020 Vehera Ltd.
 * All rights reserved. 
 *******************************************************************************/
package uk.co.scapps.cnrm;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import io.github.manusant.ss.SparkSwagger;
import io.github.manusant.ss.conf.Options;
import spark.Service;

public class ConfigIt {
	private final static Logger logger = LogManager.getLogger();
	private static Service spark;

	public static void main(String[] args) {
		CNRMProperties.getDefaultProperties();
		sparkSetup();
	}

	public static void sparkSetup() {
		int port = 8081;
		String sparkSwaggerConfigPath = "/home/dan/git/cnrm/CNRM/src/main/resources/";
		logger.info("sparkSwaggerConfigPath:" + sparkSwaggerConfigPath);
		String address = "localhost";
		Options options = Options.defaultOptions().confPath(sparkSwaggerConfigPath + SparkSwagger.CONF_FILE_NAME)
				.version("1.0.2").build();
		
		logger.info("Value of options.confPath: " + options.getConfPath());
		listFilesUsingJavaIO(sparkSwaggerConfigPath);
		showStartOfFile(options);
		
		spark = Service.ignite().ipAddress(address).port(port);
		spark.staticFiles.externalLocation(System.getProperty("java.io.tmpdir"));
		logger.info("About to run SparkSwagger.of()");
		SparkSwagger.of(spark, options);
	}

	public static void listFilesUsingJavaIO(String dir) {
		Set<String> confFiles = Stream.of(new File(dir).listFiles()).filter(file -> !file.isDirectory())
				.map(File::getName).collect(Collectors.toSet());
		logger.info("Files in sparkSwaggerConfigPath directory: ");
		for (String fileName : confFiles) {
			System.out.println(fileName);
		}

	}

	public static void showStartOfFile(Options options) {
		Scanner input = null;
		try {
			input = new Scanner(new File(options.getConfPath()));
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		logger.info("First few lines of: " + options.getConfPath());
		for (int lineNo = 0; lineNo < 5; lineNo++) {
			System.out.println(input.nextLine());
		}
	}
}


[INFO ] 2021-12-19 20:44:57.649 [main] ConfigIt - sparkSwaggerConfigPath:/home/dan/git/cnrm/CNRM/src/main/resources/
[INFO ] 2021-12-19 20:44:57.658 [main] ConfigIt - Value of options.confPath: /home/dan/git/cnrm/CNRM/src/main/resources/spark-swagger.conf
[INFO ] 2021-12-19 20:44:57.660 [main] ConfigIt - Files in sparkSwaggerConfigPath directory: 
spark-swagger.conf
[INFO ] 2021-12-19 20:44:57.664 [main] ConfigIt - First few lines of: /home/dan/git/cnrm/CNRM/src/main/resources/spark-swagger.conf
spark-swagger {

  # UI related configs
  theme = "MATERIAL"
  deepLinking = false
[main] INFO spark.staticfiles.StaticFilesConfiguration - External StaticResourceHandler configured with folder = /tmp
[main] WARN spark.staticfiles.StaticFilesFolder - Registering external static files folder [/tmp] as [/tmp].
[INFO ] 2021-12-19 20:44:57.701 [main] ConfigIt - About to run SparkSwagger.of()
Exception in thread "main" com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'spark-swagger'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:156)
	at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:149)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
	at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:250)
	at io.github.manusant.ss.SparkSwagger.<init>(SparkSwagger.java:45)
	at io.github.manusant.ss.SparkSwagger.of(SparkSwagger.java:71)
	at uk.co.scapps.cnrm.ConfigIt.sparkSetup(ConfigIt.java:45)
	at uk.co.scapps.cnrm.ConfigIt.main(ConfigIt.java:27)

```
The error message does not say that the file is not found and might be attributed to a problem with the contents of the config file, but this second program seems to show that when the same file is loaded using the default location spark-swagger loads it without error:
```
 /*******************************************************************************
 * Copyright (c) 2017, 2018, 2019, 2020 Vehera Ltd.
 * All rights reserved. 
 *******************************************************************************/
package uk.co.scapps.cnrm;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import io.github.manusant.ss.SparkSwagger;
import spark.Service;

public class NoPath {
	private final static Logger logger = LogManager.getLogger();
	private static Service spark;

	public static void main(String[] args) {
		sparkSetup();
	}

	public static void sparkSetup() {

		spark = Service.ignite().ipAddress("192.168.1.105").port(8081);
		logger.info("About to run SparkSwagger.of()");
		spark.staticFiles.externalLocation(System.getProperty("java.io.tmpdir"));
		SparkSwagger.of(spark);
	}
}

[INFO ] 2021-12-19 20:49:08.564 [main] NoPath - About to run SparkSwagger.of()
[main] INFO spark.staticfiles.StaticFilesConfiguration - External StaticResourceHandler configured with folder = /tmp
[main] WARN spark.staticfiles.StaticFilesFolder - Registering external static files folder [/tmp] as [/tmp].
[main] WARN spark.Spark - External static file location has already been set
[Thread-0] INFO org.eclipse.jetty.util.log - Logging initialized @1306ms
[Thread-0] INFO spark.embeddedserver.jetty.EmbeddedJettyServer - == Spark has ignited ...
[Thread-0] INFO spark.embeddedserver.jetty.EmbeddedJettyServer - >> Listening on 192.168.1.105:8081
[Thread-0] INFO org.eclipse.jetty.server.Server - jetty-9.3.6.v20151106
[Thread-0] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@2c1ef464{HTTP/1.1,[http/1.1]}{192.168.1.105:8081}
[Thread-0] INFO org.eclipse.jetty.server.Server - Started @1442ms
```

**Comment by manusant** [comment]
Fixed in version 2.0.6
