### ISSUE TITLE
Exception thrown if conf file does not have an externalDoc entry

### ISSUE THREAD

**Issue by johnmgithub** [manusant/spark-swagger#47]
spark-swagger 2.0.7

com.typesafe.config.ConfigException$Missing: spark-swagger.conf: 23: No configuration setting found for key 'spark-swagger.info.externalDoc'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:156)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:174)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:180)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:180)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
	at com.typesafe.config.impl.SimpleConfig.getObject(SimpleConfig.java:268)
	at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:274)
	at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:41)
	at io.github.manusant.ss.SparkSwagger.getInfo(SparkSwagger.java:249)

**Comment by manusant** [comment]
The info.externalDoc shouldn't be required. I'll have a look.

**Comment by manusant** [comment]
It should be fixed in version 2.0.8. Please test and let me know.

**Comment by johnmgithub** [comment]
All good now, thanks.
